export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const FETCH_SUPERHEROES = 'FETCH_SUPERHEROES';
export const FETCH_SUPERHEROES_SUCCESS = 'FETCH_SUPERHEROES_SUCCESS';
export const FETCH_SUPERHEROES_ERROR = 'FETCH_SUPERHEROES_ERROR';
export const DELETE_SUPERHERO = 'DELETE_SUPERHERO';
export const DELETE_SUPERHERO_SUCCESS = 'DELETE_SUPERHERO_SUCCESS';
export const DELETE_SUPERHERO_ERROR = 'DELETE_SUPERHERO_ERROR';
